name: Test Environment Variables Extraction
on:
  workflow_dispatch:
jobs:
  test-env-vars:
    runs-on: ubuntu-latest
    steps:
      - name: 환경변수 추출 테스트
        id: export-env
        env: ${{ secrets }}
        run: |
          # 현재 환경변수 출력
          echo "모든 환경변수 목록:"
          env | sort
          
          # ENV_ 접두사를 가진 환경변수만 추출하여 -D 형식으로 변환
          JAVA_OPTS=""
          for var in $(env | grep "^ENV_" | cut -d= -f1); do
            echo "변환 중인 변수: $var"
            val=$(eval echo \$${var})
            var_name=${var#ENV_}
            JAVA_OPTS="$JAVA_OPTS -D$var_name=$val"
          done
          echo "생성된 JAVA_OPTS: $JAVA_OPTS"
          
          # GitHub 출력 변수로 저장
          echo "java_opts=$JAVA_OPTS" >> $GITHUB_OUTPUT
      
      - name: 출력 변수 사용 테스트
        run: |
          # 이전 단계에서 생성한 출력 변수 사용
          echo "이전 단계에서 생성된 JAVA_OPTS: ${{ steps.export-env.outputs.java_opts }}"
          
          # 테스트용 로컬 변수 설정
          JAVA_OPTS="${{ steps.export-env.outputs.java_opts }}"
          echo "로컬 변수로 할당된 JAVA_OPTS: $JAVA_OPTS"
